-- ============================================
-- 1. USERS TABLE
-- ============================================
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(20),
    ROLE VARCHAR2(20) NOT NULL CHECK (ROLE IN ('Admin', 'Customer')),
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    CREATED_DATE DATE DEFAULT SYSDATE
);

-- ============================================
-- 2. ROOM_TYPES TABLE
-- ============================================
CREATE TABLE ROOM_TYPES (
    ROOM_TYPE_ID NUMBER PRIMARY KEY,
    TYPE_NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    BASE_PRICE NUMBER(10,2) NOT NULL CHECK (BASE_PRICE >= 0),
    MAX_GUESTS NUMBER NOT NULL CHECK (MAX_GUESTS > 0),
    IMAGE_URL VARCHAR2(255)
);

-- ============================================
-- 3. ROOMS TABLE
-- ============================================
CREATE TABLE ROOMS (
    ROOM_ID NUMBER PRIMARY KEY,
    ROOM_NUMBER VARCHAR2(10) UNIQUE NOT NULL,
    ROOM_TYPE_ID NUMBER NOT NULL,
    FLOOR_NUMBER NUMBER,
    STATUS VARCHAR2(20) DEFAULT 'Available' CHECK (STATUS IN ('Available', 'Occupied', 'Maintenance')),
    CONSTRAINT FK_ROOMS_ROOM_TYPE FOREIGN KEY (ROOM_TYPE_ID) 
        REFERENCES ROOM_TYPES(ROOM_TYPE_ID) ON DELETE CASCADE
);

-- ============================================
-- 4. BOOKINGS TABLE
-- ============================================
CREATE TABLE BOOKINGS (
    BOOKING_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ROOM_ID NUMBER NOT NULL,
    CHECK_IN_DATE DATE NOT NULL,
    CHECK_OUT_DATE DATE NOT NULL,
    NUMBER_OF_GUESTS NUMBER NOT NULL CHECK (NUMBER_OF_GUESTS > 0),
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    BOOKING_STATUS VARCHAR2(20) DEFAULT 'Pending' CHECK (BOOKING_STATUS IN ('Pending', 'Confirmed', 'Completed', 'Cancelled')),
    BOOKING_DATE DATE DEFAULT SYSDATE,
    SPECIAL_REQUESTS VARCHAR2(500),
    CONSTRAINT FK_BOOKINGS_USER FOREIGN KEY (USER_ID) 
        REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKINGS_ROOM FOREIGN KEY (ROOM_ID) 
        REFERENCES ROOMS(ROOM_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_DATES CHECK (CHECK_OUT_DATE > CHECK_IN_DATE)
);

-- ============================================
-- 5. SERVICES TABLE
-- ============================================
CREATE TABLE SERVICES (
    SERVICE_ID NUMBER PRIMARY KEY,
    SERVICE_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    PRICE NUMBER(10,2) NOT NULL CHECK (PRICE >= 0),
    IS_AVAILABLE NUMBER(1) DEFAULT 1 CHECK (IS_AVAILABLE IN (0, 1))
);

-- ============================================
-- 6. BOOKING_SERVICES TABLE
-- ============================================
CREATE TABLE BOOKING_SERVICES (
    BOOKING_SERVICE_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL,
    SERVICE_ID NUMBER NOT NULL,
    QUANTITY NUMBER DEFAULT 1 CHECK (QUANTITY > 0),
    TOTAL_PRICE NUMBER(10,2) NOT NULL CHECK (TOTAL_PRICE >= 0),
    CONSTRAINT FK_BOOKING_SERVICES_BOOKING FOREIGN KEY (BOOKING_ID) 
        REFERENCES BOOKINGS(BOOKING_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKING_SERVICES_SERVICE FOREIGN KEY (SERVICE_ID) 
        REFERENCES SERVICES(SERVICE_ID) ON DELETE CASCADE
);

-- ============================================
-- 7. PAYMENTS TABLE
-- ============================================
CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL,
    PAYMENT_DATE DATE DEFAULT SYSDATE,
    AMOUNT NUMBER(10,2) NOT NULL CHECK (AMOUNT >= 0),
    PAYMENT_METHOD VARCHAR2(50) CHECK (PAYMENT_METHOD IN ('Cash', 'Credit Card', 'Debit Card', 'Online')),
    PAYMENT_STATUS VARCHAR2(20) CHECK (PAYMENT_STATUS IN ('Completed', 'Failed')),
    CONSTRAINT FK_PAYMENTS_BOOKING FOREIGN KEY (BOOKING_ID) 
        REFERENCES BOOKINGS(BOOKING_ID) ON DELETE CASCADE
);

-- ============================================
-- 8. REVIEWS TABLE
-- ============================================
CREATE TABLE REVIEWS (
    REVIEW_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    RATING NUMBER(1) CHECK (RATING BETWEEN 1 AND 5),
    REVIEW_COMMENT VARCHAR2(1000), 
    REVIEW_DATE DATE DEFAULT SYSDATE
);

-- إضافة Foreign Keys
ALTER TABLE REVIEWS 
ADD CONSTRAINT FK_REVIEWS_BOOKING 
FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS(BOOKING_ID);

ALTER TABLE REVIEWS 
ADD CONSTRAINT FK_REVIEWS_USER 
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
-- ============================================
-- SEQUENCES FOR AUTO-INCREMENT IDs
-- ============================================

-- Sequence for USERS
CREATE SEQUENCE SEQ_USERS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for ROOM_TYPES
CREATE SEQUENCE SEQ_ROOM_TYPES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for ROOMS
CREATE SEQUENCE SEQ_ROOMS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for BOOKINGS
CREATE SEQUENCE SEQ_BOOKINGS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for SERVICES
CREATE SEQUENCE SEQ_SERVICES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for BOOKING_SERVICES
CREATE SEQUENCE SEQ_BOOKING_SERVICES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for PAYMENTS
CREATE SEQUENCE SEQ_PAYMENTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for REVIEWS
CREATE SEQUENCE SEQ_REVIEWS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    -- ============================================
-- TRIGGERS FOR AUTO-INCREMENT
-- ============================================

-- Trigger for USERS
CREATE OR REPLACE TRIGGER TRG_USERS_BI
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT SEQ_USERS.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;
END;
/

-- Trigger for ROOM_TYPES
CREATE OR REPLACE TRIGGER TRG_ROOM_TYPES_BI
BEFORE INSERT ON ROOM_TYPES
FOR EACH ROW
BEGIN
    IF :NEW.ROOM_TYPE_ID IS NULL THEN
        SELECT SEQ_ROOM_TYPES.NEXTVAL INTO :NEW.ROOM_TYPE_ID FROM DUAL;
    END IF;
END;
/

-- Trigger for ROOMS
CREATE OR REPLACE TRIGGER TRG_ROOMS_BI
BEFORE INSERT ON ROOMS
FOR EACH ROW
BEGIN
    IF :NEW.ROOM_ID IS NULL THEN
        SELECT SEQ_ROOMS.NEXTVAL INTO :NEW.ROOM_ID FROM DUAL;
    END IF;
END;
/

-- Trigger for BOOKINGS
CREATE OR REPLACE TRIGGER TRG_BOOKINGS_BI
BEFORE INSERT ON BOOKINGS
FOR EACH ROW
BEGIN
    IF :NEW.BOOKING_ID IS NULL THEN
        SELECT SEQ_BOOKINGS.NEXTVAL INTO :NEW.BOOKING_ID FROM DUAL;
    END IF;
END;
/

-- Trigger for SERVICES
CREATE OR REPLACE TRIGGER TRG_SERVICES_BI
BEFORE INSERT ON SERVICES
FOR EACH ROW
BEGIN
    IF :NEW.SERVICE_ID IS NULL THEN
        SELECT SEQ_SERVICES.NEXTVAL INTO :NEW.SERVICE_ID FROM DUAL;
    END IF;
END;
/

-- Trigger for BOOKING_SERVICES
CREATE OR REPLACE TRIGGER TRG_BOOKING_SERVICES_BI
BEFORE INSERT ON BOOKING_SERVICES
FOR EACH ROW
BEGIN
    IF :NEW.BOOKING_SERVICE_ID IS NULL THEN
        SELECT SEQ_BOOKING_SERVICES.NEXTVAL INTO :NEW.BOOKING_SERVICE_ID FROM DUAL;
    END IF;
END;
/

-- Trigger for PAYMENTS
CREATE OR REPLACE TRIGGER TRG_PAYMENTS_BI
BEFORE INSERT ON PAYMENTS
FOR EACH ROW
BEGIN
    IF :NEW.PAYMENT_ID IS NULL THEN
        SELECT SEQ_PAYMENTS.NEXTVAL INTO :NEW.PAYMENT_ID FROM DUAL;
    END IF;
END;
/

-- Trigger for REVIEWS
CREATE OR REPLACE TRIGGER TRG_REVIEWS_BI
BEFORE INSERT ON REVIEWS
FOR EACH ROW
BEGIN
    IF :NEW.REVIEW_ID IS NULL THEN
        SELECT SEQ_REVIEWS.NEXTVAL INTO :NEW.REVIEW_ID FROM DUAL;
    END IF;
END;
/





-- ============================================
-- INDEXES FOR BETTER PERFORMANCE
-- ============================================

-- Index on USERS email for login
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);

-- Index on USERS username for login
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);

-- Index on BOOKINGS dates for searching available rooms
CREATE INDEX IDX_BOOKINGS_DATES ON BOOKINGS(CHECK_IN_DATE, CHECK_OUT_DATE);

-- Index on BOOKINGS status
CREATE INDEX IDX_BOOKINGS_STATUS ON BOOKINGS(BOOKING_STATUS);

-- Index on ROOMS status
CREATE INDEX IDX_ROOMS_STATUS ON ROOMS(STATUS);

-- Index on REVIEWS rating
CREATE INDEX IDX_REVIEWS_RATING ON REVIEWS(RATING);

-- Composite index on BOOKINGS for user's bookings
CREATE INDEX IDX_BOOKINGS_USER_DATE ON BOOKINGS(USER_ID, BOOKING_DATE);


-- ============================================
-- INSERT SAMPLE DATA
-- ============================================

-- Insert Admin User (password: admin123)
INSERT INTO USERS (USERNAME, PASSWORD_HASH, EMAIL, FULL_NAME, PHONE, ROLE) 
VALUES ('admin', 'admin123hash', 'admin@hotel.com', 'Administrator', '01234567890', 'Admin');

-- Insert Sample Customer (password: customer123)
INSERT INTO USERS (USERNAME, PASSWORD_HASH, EMAIL, FULL_NAME, PHONE, ROLE) 
VALUES ('john_doe', 'customer123hash', 'john@email.com', 'John Doe', '01111111111', 'Customer');

INSERT INTO USERS (USERNAME, PASSWORD_HASH, EMAIL, FULL_NAME, PHONE, ROLE) 
VALUES ('jane_smith', 'customer123hash', 'jane@email.com', 'Jane Smith', '01222222222', 'Customer');

-- Insert Room Types
INSERT INTO ROOM_TYPES (TYPE_NAME, DESCRIPTION, BASE_PRICE, MAX_GUESTS, IMAGE_URL) 
VALUES ('Single Room', 'Comfortable single room with all amenities', 100.00, 1, '/images/single.jpg');

INSERT INTO ROOM_TYPES (TYPE_NAME, DESCRIPTION, BASE_PRICE, MAX_GUESTS, IMAGE_URL) 
VALUES ('Double Room', 'Spacious double room perfect for couples', 150.00, 2, '/images/double.jpg');

INSERT INTO ROOM_TYPES (TYPE_NAME, DESCRIPTION, BASE_PRICE, MAX_GUESTS, IMAGE_URL) 
VALUES ('Suite', 'Luxury suite with living area and premium amenities', 300.00, 4, '/images/suite.jpg');

INSERT INTO ROOM_TYPES (TYPE_NAME, DESCRIPTION, BASE_PRICE, MAX_GUESTS, IMAGE_URL) 
VALUES ('Deluxe Room', 'Deluxe room with sea view and balcony', 250.00, 2, '/images/deluxe.jpg');

-- Insert Rooms
INSERT INTO ROOMS (ROOM_NUMBER, ROOM_TYPE_ID, FLOOR_NUMBER, STATUS) 
VALUES ('101', 1, 1, 'Available');

INSERT INTO ROOMS (ROOM_NUMBER, ROOM_TYPE_ID, FLOOR_NUMBER, STATUS) 
VALUES ('102', 1, 1, 'Available');

INSERT INTO ROOMS (ROOM_NUMBER, ROOM_TYPE_ID, FLOOR_NUMBER, STATUS) 
VALUES ('201', 2, 2, 'Available');

INSERT INTO ROOMS (ROOM_NUMBER, ROOM_TYPE_ID, FLOOR_NUMBER, STATUS) 
VALUES ('202', 2, 2, 'Available');

INSERT INTO ROOMS (ROOM_NUMBER, ROOM_TYPE_ID, FLOOR_NUMBER, STATUS) 
VALUES ('301', 3, 3, 'Available');

INSERT INTO ROOMS (ROOM_NUMBER, ROOM_TYPE_ID, FLOOR_NUMBER, STATUS) 
VALUES ('401', 4, 4, 'Available');

-- Insert Services
INSERT INTO SERVICES (SERVICE_NAME, DESCRIPTION, PRICE, IS_AVAILABLE) 
VALUES ('Room Service', '24/7 room service', 20.00, 1);

INSERT INTO SERVICES (SERVICE_NAME, DESCRIPTION, PRICE, IS_AVAILABLE) 
VALUES ('Laundry', 'Laundry and dry cleaning service', 15.00, 1);

INSERT INTO SERVICES (SERVICE_NAME, DESCRIPTION, PRICE, IS_AVAILABLE) 
VALUES ('Airport Transfer', 'Pick up and drop off service', 50.00, 1);

INSERT INTO SERVICES (SERVICE_NAME, DESCRIPTION, PRICE, IS_AVAILABLE) 
VALUES ('Spa & Massage', 'Relaxing spa and massage services', 80.00, 1);

INSERT INTO SERVICES (SERVICE_NAME, DESCRIPTION, PRICE, IS_AVAILABLE) 
VALUES ('Breakfast Buffet', 'Continental breakfast buffet', 25.00, 1);

-- Commit all changes
COMMIT;