CREATE OR REPLACE PROCEDURE UPDATE_ROOM_TYPE (
    ROOM_TYPE_ID IN ROOM_TYPES.ROOM_TYPE_ID%TYPE,
    TYPE_NAME    IN ROOM_TYPES.TYPE_NAME%TYPE,
    DESCRIPTION  IN ROOM_TYPES.DESCRIPTION%TYPE,
    BASE_PRICE   IN ROOM_TYPES.BASE_PRICE%TYPE,
    MAX_GUESTS   IN ROOM_TYPES.MAX_GUESTS%TYPE,
    IMAGE_URL    IN ROOM_TYPES.IMAGE_URL%TYPE
)
AS
BEGIN
    UPDATE ROOM_TYPES
    SET
        TYPE_NAME   = UPDATE_ROOM_TYPE.TYPE_NAME,
        DESCRIPTION = UPDATE_ROOM_TYPE.DESCRIPTION,
        BASE_PRICE  = UPDATE_ROOM_TYPE.BASE_PRICE,
        MAX_GUESTS  = UPDATE_ROOM_TYPE.MAX_GUESTS,
        IMAGE_URL   = UPDATE_ROOM_TYPE.IMAGE_URL
    WHERE ROOM_TYPE_ID = UPDATE_ROOM_TYPE.ROOM_TYPE_ID;
 
    COMMIT;
END;
/
 